CREATE PROCEDURE [dbo].[CRE_CHOFER_PR]
	@P_CEDULA NVARCHAR(50),
	@P_NOMBRE NVARCHAR(50),
	@P_APELLIDOS NVARCHAR(50),
	@P_TELEFONO NVARCHAR(8),
	@P_CORREO NVARCHAR(50),
	@P_FECHA_NACIMIENTO DATE,
	@P_EDAD INT,
	@P_NUMERO_LICENCIA NVARCHAR(11),
	@P_FECHA_EXPIRACION DATE,
	@P_EMPRESA int,
	@P_ESTADO NVARCHAR(10)
AS
	INSERT INTO TBL_CHOFER VALUES (@P_CEDULA, @P_NOMBRE, @P_APELLIDOS, @P_TELEFONO, @P_CORREO, @P_FECHA_NACIMIENTO, @P_EDAD, @P_NUMERO_LICENCIA, @P_FECHA_EXPIRACION, @P_EMPRESA, @P_ESTADO)
RETURN 0
