CREATE PROCEDURE [dbo].[CRE_MULTA_PR]
	@P_EMPRESA nvarchar(50),
	@P_MONTO int,
	@P_FECHA datetime,
	@P_DETALLE nvarchar(500),
	@P_ESTADO nvarchar(10)
AS
	INSERT INTO TBL_MULTA VALUES (@P_EMPRESA, @P_MONTO, @P_FECHA, @P_DETALLE, @P_ESTADO)
RETURN 0
