CREATE PROCEDURE [dbo].[CRE_BUS_PR]
	@P_PLACA nvarchar(50),
	@P_CAPACIDAD_SENTADO int,
	@P_CAPACIDAD_DEPIE int,
	@P_ASIENTO_DISCAPACITADO int,
	@P_EMPRESA int
AS
	INSERT INTO TBL_BUS(
		PLACA,
		CAPACIDAD_SENTADO,
		CAPACIDAD_DEPIE,
		ASIENTO_DISCAPACITADO,
		ESTADO,
		EMPRESA
	)
	VALUES(
		@P_PLACA,
		@P_CAPACIDAD_SENTADO,
		@P_CAPACIDAD_DEPIE,
		@P_ASIENTO_DISCAPACITADO,
		'Activo',
		@P_EMPRESA
	)

RETURN 0
