CREATE PROCEDURE [dbo].[CRE_SANCION_PR]
	@P_DESCRIPCION NVARCHAR (100),
	@P_MULTA INT,
	@P_ESTADO nvarchar(10),
	@P_TERMINAL_ID INT,
	@P_FECHA DATETIME,
	@P_SUSPENCION nvarchar(10),
	@P_FECHA_REACTIVACION DATETIME,
	@P_EMPRESA int
AS
	INSERT INTO [dbo].[TBL_SANCION] VALUES(@P_DESCRIPCION,@P_MULTA,@P_ESTADO, @P_TERMINAL_ID, @P_FECHA, @P_SUSPENCION, @P_FECHA_REACTIVACION, @P_EMPRESA);
RETURN 0

