CREATE PROCEDURE [dbo].[CRE_EMPRESA_PR]
	@P_CEDULA_JURIDICA int,
	@P_NOMBRE_EMPRESA nvarchar(45),
	@P_EMAIL_ENCARGADO nvarchar(50),
	@P_TELEFONO nvarchar(50)
AS
	INSERT INTO TBL_EMPRESA(
		CEDULA_JURIDICA,
		NOMBRE_EMPRESA,
		EMAIL_ENCARGADO,
		TELEFONO,
		ESTADO
	)
	VALUES(
		@P_CEDULA_JURIDICA,
		@P_NOMBRE_EMPRESA,
		@P_EMAIL_ENCARGADO,
		@P_TELEFONO,
		'Pendiente'
	)

RETURN 0
