CREATE PROCEDURE [dbo].[CRE_CONFIGURACION_TERMINAL_PR]
	@P_TERMINAL_ID int
    ,@P_CANTIDAD_QUEJAS_SANCION int
    ,@P_COSTO_PARQUEO_HORA decimal(18,2)
    ,@P_COSTO_PARQUEO_DIA decimal(18,2)
    ,@P_MONTO_INICIAL_TARJETA decimal(18,2)
	,@P_COSTO_PARQUEO_BUS_MES decimal(18,2)
	,@P_CANTIDAD_MINUTOS_TARDIA INT
	,@P_CANTIDAD_TARDIAS_SANCION int
AS
	INSERT INTO [dbo].[TBL_CONFIGURACION_TERMINAL]
           ([TERMINAL_ID]
           ,[CANTIDAD_QUEJAS_SANCION]
           ,[COSTO_PARQUEO_HORA]
           ,[COSTO_PARQUEO_DIA]
           ,[MONTO_INICIAL_TARJETA]
		   ,[COSTO_PARQUEO_BUS_MES]
		   ,[CANTIDAD_MINUTOS_TARDIA]
		   ,[CANTIDAD_TARDIAS_SANCION])
     VALUES
           (@P_TERMINAL_ID
           ,@P_CANTIDAD_QUEJAS_SANCION
           ,@P_COSTO_PARQUEO_HORA
           ,@P_COSTO_PARQUEO_DIA
           ,@P_MONTO_INICIAL_TARJETA
		   ,@P_COSTO_PARQUEO_BUS_MES
		   ,@P_CANTIDAD_MINUTOS_TARDIA
		   ,@P_CANTIDAD_TARDIAS_SANCION)
RETURN 0
