CREATE PROCEDURE [dbo].[CRE_SALIDA_PARQUEO_PR]
	@P_TARJETA_ID nvarchar(50),
	@P_TERMINAL_ID int,
	@P_HORA_FIN datetime,
	@P_COSTO_TOTAL int
AS 
	UPDATE  TBL_REGISTROPARQUEO
		SET           
		   HORA_FIN = @P_HORA_FIN,
		   COSTO_TOTAL = @P_COSTO_TOTAL

		   where TARJETA_ID = @P_TARJETA_ID
		   AND TERMINAL_ID = @P_TERMINAL_ID
		   AND HORA_FIN IS NULL
		   AND COSTO_TOTAL IS NULL OR COSTO_TOTAL < 0
Return 0