CREATE PROCEDURE [dbo].[RET_HISTORIAL_CONTRASENA_PR]
	@P_EMAIL nvarchar(50),
	@P_PASSWORD_HASH nvarchar(24),
	@P_COUNT int
AS
	SELECT * 
	FROM (SELECT TOP (@P_COUNT) *
		  FROM [dbo].[TBL_HISTORIAL_PASSWORD]
		  WHERE [EMAIL] = @P_EMAIL
		  ORDER BY [PASSWORD_SET] DESC) AS HISTORIAL
	WHERE [EMAIL] = @P_EMAIL AND [PASSWORD_HASH] = @P_PASSWORD_HASH
RETURN 0
