CREATE PROCEDURE [dbo].[RET_VISTA_ROLE_PR]
	@P_ROLE_ID nvarchar(50)
AS
	SELECT TBL_VISTA.* FROM TBL_ROLE_VISTA
	INNER JOIN TBL_VISTA ON TBL_ROLE_VISTA.VISTA_ID = TBL_VISTA.VISTA_ID
	WHERE TBL_ROLE_VISTA.ROLE_ID = @P_ROLE_ID
RETURN 0
