CREATE PROCEDURE [dbo].[RET_APP_CLAIM_ROLE_PR]
	@P_ROLE_ID nvarchar(50)
AS
	SELECT TBL_APP_CLAIM.* FROM TBL_VISTA_CLAIM
	INNER JOIN TBL_APP_CLAIM ON TBL_APP_CLAIM.APP_CLAIM_ID = TBL_VISTA_CLAIM.APP_CLAIM_ID
	INNER JOIN TBL_ROLE_VISTA ON TBL_ROLE_VISTA.VISTA_ID = TBL_VISTA_CLAIM.VISTA_ID
	WHERE TBL_ROLE_VISTA.ROLE_ID = @P_ROLE_ID
RETURN 0
