CREATE PROCEDURE [dbo].[RET_ESPACIO_DISPONIBLE_PARQUEO]
	@P_TERMINAL_ID int 
AS
	select SUM(ESPACIOS_PARQUEO) as ESPACIOS_PARQUEO from TBL_LINEA
	where TERMINAL_ID = @P_TERMINAL_ID
	group by TERMINAL_ID
RETURN 0
