CREATE PROCEDURE [dbo].[RET_RUTA_PR]
	@P_RUTA_ID int
AS
	SELECT [TBL_RUTA].*
	  ,[TBL_TARIFA].[REGULAR_FARE] AS COSTO_TOTAL
	  ,([TBL_TARIFA].[REGULAR_FARE]/[DISTANCIA]) AS COSTO_KM
	  ,[TBL_TARIFA].[ROUTE_NAME] AS RUTA_NAME
	  ,[TBL_LINEA].EMPRESA_ID AS EMPRESA_ID
  FROM [dbo].[TBL_RUTA]
  INNER JOIN [TBL_TARIFA]
  ON [TBL_TARIFA].[ROUTE_ID] = [TARIFA_ID]
  INNER JOIN [TBL_LINEA] 
  ON [TBL_RUTA].LINEA_ID = [TBL_LINEA].LINEA_ID
  WHERE [RUTA_ID] = @P_RUTA_ID
RETURN 0
