CREATE PROCEDURE [dbo].[RET_RECORRIDO_TARDIA_MES_PR]
AS
	SELECT *
	FROM [dbo].[TBL_RECORRIDO]
	WHERE DATEPART(m,[HORA_SALIDA]) = DATEPART(m,GETDATE()) AND DATEPART(yy,[HORA_SALIDA]) = DATEPART(yy,GETDATE()) AND [TARDIA] > 0
RETURN 0
