CREATE PROCEDURE [dbo].[RET_BUS_POR_PLACA_PR]
	@P_PLACA nvarchar(50)
AS
	SELECT PLACA, EMPRESA, CAPACIDAD_SENTADO, CAPACIDAD_DEPIE, ASIENTO_DISCAPACITADO, B.ESTADO, NOMBRE_EMPRESA 
	FROM TBL_BUS B 
	INNER JOIN TBL_EMPRESA E ON B.EMPRESA = E.CEDULA_JURIDICA
	WHERE PLACA = @P_PLACA

RETURN 0
