CREATE PROCEDURE [dbo].[RET_ALL_TRANSACTIONS_BY_TERMID]
	@P_TERMINAL_ID int
AS
	Select tr.*, t.USUARIO as EMAIL from TBL_TRANSACCION as tr
	join TBL_TARJETA  t on t.CODIGO_UNICO = tr.TARJETA_ID
	where tr.TERMINAL_ID = @P_TERMINAL_ID
	union
	Select tr.*, t.NOMBRE_LINEA as EMAIL from TBL_TRANSACCION as tr
	join TBL_LINEA  t on t.LINEA_ID = tr.LINEA_ID
	where tr.TERMINAL_ID = @P_TERMINAL_ID
RETURN 0
