CREATE PROCEDURE [dbo].[RET_QUEJAS_ACTIVA_PR]
AS
	SELECT *
	FROM [TBL_QUEJAS]
	WHERE [ESTADO] = 'Activo'

	--SELECT TBL_QUEJAS.*, TBL_CHOFER.NOMBRE, TBL_CHOFER.APELLIDOS
	--FROM [TBL_QUEJAS]
	--INNER JOIN TBL_CHOFER ON TBL_CHOFER.CEDULA = CEDULA
	--SELECT *
	--FROM [TBL_QUEJAS]
	--WHERE [ESTADO] = 'Activo'
RETURN 0
