CREATE PROCEDURE [dbo].[RET_ESPACIOS_DISPONIBLES_PR]
	@P_TERMINAL_ID nvarchar(50)
AS

SELECT
(
	(select ESPACIOS_PARQUEO FROM TBL_TERMINAL 
		WHERE TERMINAL_ID = @P_TERMINAL_ID
	) -
	(select count(REGISTRO_PARQUEO_ID) as PARQUEADOS FROM TBL_REGISTROPARQUEO 
		WHERE TERMINAL_ID = @P_TERMINAL_ID AND HORA_FIN IS NULL
	)
) ESPACIOSDISPONIBLES

RETURN 0