CREATE PROCEDURE [dbo].[RET_TIPO_TARJETA_BY_ID]
	@P_TIPOTARJETA_ID int = 0,	
	@P_NOMBRE_TARJETA NVARCHAR(45) = ''
AS
	SELECT * 
	From TBL_TIPOTARJETA
	where (NOMBRE_TARJETA = @P_NOMBRE_TARJETA or TIPOTARJETA_ID = @P_TIPOTARJETA_ID)
		 and STATUS <> 0
Go