CREATE PROCEDURE [dbo].[RET_ALL_BUS_PR]
AS
	SELECT PLACA, EMPRESA, CAPACIDAD_SENTADO, CAPACIDAD_DEPIE, ASIENTO_DISCAPACITADO, B.ESTADO, NOMBRE_EMPRESA 
	FROM TBL_BUS B 
	INNER JOIN TBL_EMPRESA E ON B.EMPRESA = E.CEDULA_JURIDICA

RETURN 0
