CREATE PROCEDURE [dbo].[RET_ALL_SANCION_ACTIVAS_PR]
AS
	SELECT TBL_SANCION.*, TBL_EMPRESA.NOMBRE_EMPRESA
	FROM [TBL_SANCION]
	Inner join TBL_EMPRESA ON TBL_EMPRESA.CEDULA_JURIDICA = EMPRESA
	WHERE [TBL_SANCION].ESTADO = 'Activo'

RETURN 0
