CREATE PROCEDURE [dbo].[RET_CONVENIO_BY_TERMINAL_ID]
	@P_TERMINAL_ID int 
AS
	SELECT c.* from TBL_CONVENIO as c
	join TBL_CONVENIO_TERMINAL as ct
	on ct.CEDULA_JURIDICA = c.CEDULA_JURIDICA
	where ct.TERMINAL_ID = @P_TERMINAL_ID
RETURN 0
