CREATE PROCEDURE [dbo].[UPD_MULTA_PR]
	@P_MULTA_ID INT,
	@P_EMPRESA int,
	@P_MONTO int,
	@P_FECHA datetime,
	@P_DETALLE nvarchar(500),
	@P_ESTADO nvarchar(10)
AS
	UPDATE TBL_MULTA
		SET 
		EMPRESA = @P_EMPRESA,
		MONTO = @P_MONTO,
		FECHA = @P_FECHA,
		DETALLE = @P_DETALLE,
		ESTADO = @P_ESTADO

		WHERE MULTA_ID = @P_MULTA_ID
RETURN 0
