CREATE PROCEDURE [dbo].[UPD_EMPRESA_PENDIENTE_PR]
	@P_NOMBRE_EMPRESA nvarchar(50),
	@P_ESTADO nvarchar(50)
AS
	UPDATE TBL_EMPRESA
	SET ESTADO = @P_ESTADO
	WHERE NOMBRE_EMPRESA = @P_NOMBRE_EMPRESA

RETURN 0

