CREATE PROCEDURE [dbo].[UPD_TARJETA_ESTADO_PR]
    @P_CODIGO_UNICO nvarchar(50),
	@P_ESTADO_TARJETA_ID int
AS 
	Begin
		SET NOCOUNT ON;  
		UPDATE  TBL_TARJETA
		SET           
		   ESTADO_TARJETA_ID = @P_ESTADO_TARJETA_ID
		   where CODIGO_UNICO = @P_CODIGO_UNICO
	End
GO  
