CREATE PROCEDURE [dbo].[UPD_LINEA_PR]
	@P_LINEA_ID int,
	@P_NOMBRE_LINEA Nvarchar(45),
	@P_TERMINAL_ID int,
	@P_EMPRESA_ID int,
	@P_ESPACIOS_PARQUEO int
AS
	Begin
		SET NOCOUNT ON;  
		UPDATE  TBL_LINEA
		SET
            NOMBRE_LINEA = @P_NOMBRE_LINEA,
			TERMINAL_ID = @P_TERMINAL_ID,
			EMPRESA_ID = @P_EMPRESA_ID,
			ESPACIOS_PARQUEO = @P_ESPACIOS_PARQUEO
			WHERE LINEA_ID =@P_LINEA_ID
	END
GO
