CREATE PROCEDURE [dbo].[UPD_RUTA_PR]
	@P_RUTA_ID int,
    @P_RUTA_DESCRIPCION nvarchar(100),
    @P_JSON_ROUTE nvarchar(max),
    @P_LATITUDE_DESTINO decimal(20,17),
    @P_LONGITUDE_DESTINO decimal(20,17),
    @P_DISTANCIA decimal(10,3),
    @P_LINEA_ID int,
    @P_TERMINAL_ID int,
    @P_TARIFA_ID int,
    @P_ESTADO NVARCHAR(10)
AS
	UPDATE [dbo].[TBL_RUTA]
   SET [RUTA_DESCRIPCION] = @P_RUTA_DESCRIPCION
      ,[JSON_ROUTE] = @P_JSON_ROUTE
      ,[LATITUDE_DESTINO] = @P_LATITUDE_DESTINO
      ,[LONGITUDE_DESTINO] = @P_LONGITUDE_DESTINO
      ,[DISTANCIA] = @P_DISTANCIA
      ,[LINEA_ID] = @P_LINEA_ID
      ,[TERMINAL_ID] = @P_TERMINAL_ID
      ,[TARIFA_ID] = @P_TARIFA_ID
      ,[ESTADO] = @P_ESTADO
 WHERE [RUTA_ID] = @P_RUTA_ID
RETURN 0
