CREATE PROCEDURE [dbo].[UPD_RECORRIDO_SALIDA_PR]
	@P_RECORRIDO_ID INT,
	@P_HORA_SALIDA DATETIME,
	@P_TARDIA int
AS
	UPDATE [dbo].[TBL_RECORRIDO]
	SET [HORA_SALIDA] = @P_HORA_SALIDA
		,[TARDIA] = @P_TARDIA
	WHERE [RECORRIDO_ID] = @P_RECORRIDO_ID
RETURN 0
