CREATE PROCEDURE [dbo].[UPD_EMPRESA_PR]
	@P_NOMBRE_EMPRESA nvarchar(50),
	@P_EMAIL_ENCARGADO nvarchar(50),
	@P_TELEFONO nvarchar(50)
AS
	UPDATE TBL_EMPRESA
	SET EMAIL_ENCARGADO = @P_EMAIL_ENCARGADO,
	TELEFONO = @P_TELEFONO
	WHERE NOMBRE_EMPRESA = @P_NOMBRE_EMPRESA

RETURN 0