CREATE PROCEDURE [dbo].[UPD_SANCION_PR]
	@P_SANCION_ID int,
    @P_DESCRIPCION NVARCHAR (100),
	@P_MULTA INT,
	@P_ESTADO nvarchar(10),
	@P_TERMINAL_ID INT,
	@P_FECHA DATETIME,
	@P_SUSPENCION nvarchar(10),
	@P_FECHA_REACTIVACION DATETIME,
	@P_EMPRESA INT
AS 
	UPDATE  TBL_SANCION
		SET           
		   DESCRIPCION = @P_DESCRIPCION,
		   MULTA = @P_MULTA,
		   ESTADO = @P_ESTADO,
		   TERMINAL_ID = @P_TERMINAL_ID,
		   FECHA = @P_FECHA,
		   SUSPENCION = @P_SUSPENCION,
		   FECHA_REACTIVACION = @P_FECHA_REACTIVACION,
		   EMPRESA = @P_EMPRESA

		   where SANCION_ID = @P_SANCION_ID
Return 0
