CREATE PROCEDURE [dbo].[UPD_ROLE_ESTADO_PR]
	@P_ROLE_ID nvarchar(50)
AS
	UPDATE TBL_ROLE
	SET ESTADO = CASE WHEN ESTADO = 'Activo' THEN 'Inactivo' ELSE 'Activo' END
	WHERE ROLE_ID = @P_ROLE_ID
RETURN 0
