CREATE PROCEDURE [dbo].[UPD_TIPO_TARJETA]
	@P_TIPOTARJETA_ID int,
	@P_NOMBRE_TARJETA Nvarchar(45),
	@P_DESCUENTO_TARIFA int
AS
	Begin
		SET NOCOUNT ON;  
		UPDATE  TBL_TIPOTARJETA
		SET
            NOMBRE_TARJETA = @P_NOMBRE_TARJETA,
			DESCUENTO_TARIFA = @P_DESCUENTO_TARIFA
			WHERE TIPOTARJETA_ID =@P_TIPOTARJETA_ID
	END
GO
