CREATE PROCEDURE [dbo].[UPD_BUS_PR]
	@P_PLACA nvarchar(50),
	@P_CAPACIDAD_SENTADO int,
	@P_CAPACIDAD_DEPIE int,
	@P_ASIENTO_DISCAPACITADO int
AS
	UPDATE [dbo].[TBL_BUS]
	SET 
		CAPACIDAD_SENTADO = @P_CAPACIDAD_SENTADO,
		CAPACIDAD_DEPIE = @P_CAPACIDAD_DEPIE,
		ASIENTO_DISCAPACITADO = @P_ASIENTO_DISCAPACITADO
	WHERE PLACA = @P_PLACA

RETURN 0