CREATE PROCEDURE [dbo].[UPD_EMPRESA_ESTADO]
	@P_NOMBRE_EMPRESA nvarchar(50)
AS
	UPDATE TBL_EMPRESA
	SET ESTADO = CASE WHEN ESTADO = 'Activo' THEN 'Inactivo' ELSE 'Activo' END
	WHERE NOMBRE_EMPRESA = @P_NOMBRE_EMPRESA

RETURN 0

