CREATE TABLE [dbo].[TBL_TRANSACCION](
	[TRANSACCION_ID] [int] IDENTITY(1,1) NOT NULL,
	[MONTO] [int] NOT NULL,
	[TIPO] [nvarchar](45) NOT NULL,
	[CONCEPTO] [nvarchar](45) NOT NULL,
	[ESTADO] [nvarchar](45) NOT NULL,
	[TARJETA_ID] [nvarchar](50) NULL DEFAULT (NULL),
	[LINEA_ID] [int] NULL DEFAULT (NULL),
	[TERMINAL_ID] [int] NULL DEFAULT (NULL),
	[FECHA] DATETIME NOT NULL, 
    CONSTRAINT [PK_TBL_TRANSACCION_TRANSACCION_ID] PRIMARY KEY CLUSTERED ([TRANSACCION_ID] ASC),
	CONSTRAINT [TBL_TRANSACCION$FK_TBL_TRANSACCION_TBL_LINEA1] FOREIGN KEY([LINEA_ID]) REFERENCES [dbo].[TBL_LINEA] ([LINEA_ID]),
	CONSTRAINT [TBL_TRANSACCION$FK_TBL_TRANSACCION_TBL_TARJETA1] FOREIGN KEY([TARJETA_ID]) REFERENCES [dbo].[TBL_TARJETA] ([CODIGO_UNICO]),
	CONSTRAINT [TBL_TRANSACCION$FK_TBL_TRANSACCION_TBL_TERMINAL1] FOREIGN KEY([TERMINAL_ID]) REFERENCES [dbo].[TBL_TERMINAL] ([TERMINAL_ID])
)