CREATE TABLE [dbo].[TBL_SANCION](
	[SANCION_ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [nvarchar](100) NOT NULL,
	[MULTA] [int] NOT NULL,
	[ESTADO] NVARCHAR(10) NOT NULL,
	[TERMINAL_ID] [int] NOT NULL,
	[FECHA] DATETIME NOT NULL, 
    [SUSPENCION] NVARCHAR(10) NOT NULL, 
    [FECHA_REACTIVACION] DATETIME NULL, 
    [EMPRESA] INT NOT NULL, 
    CONSTRAINT [PK_TBL_SANCION_SANCIO_ID] PRIMARY KEY CLUSTERED ([SANCION_ID] ASC),
	CONSTRAINT [TBL_SANCION$FK_SANCION_TERMINAL] FOREIGN KEY([TERMINAL_ID]) REFERENCES [dbo].[TBL_TERMINAL] ([TERMINAL_ID])
)