CREATE TABLE [dbo].[TBL_PAGOS_PENDIENTES]
(
	[ID_PAGO] INT IDENTITY(1,1) NOT NULL,
    [LINEA_ID] INT NOT NULL, 
    [MONTO] INT NOT NULL, 
    [ESTADO_PAGO] NVARCHAR(50) NOT NULL, 
    [CEDULA_JURIDICA] INT NOT NULL, 
    [FECHA] DATETIME NOT NULL, 
    [DESCRIPCION] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK_TBL_PAGOS_PENDIENTES] PRIMARY KEY ([ID_PAGO]), 
    CONSTRAINT [FK_TBL_PAGOS_PENDIENTES_LINEA] FOREIGN KEY ([LINEA_ID]) REFERENCES [TBL_LINEA]([LINEA_ID]), 
    CONSTRAINT [FK_TBL_PAGOS_PENDIENTES_EMPRESA] FOREIGN KEY ([CEDULA_JURIDICA]) REFERENCES [TBL_EMPRESA]([CEDULA_JURIDICA])
)
