CREATE TABLE [dbo].[TBL_CHOFER]
(
	[CEDULA] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [NOMBRE] NVARCHAR(50) NOT NULL, 
    [APELLIDOS] NVARCHAR(50) NOT NULL, 
    [TELEFONO] NVARCHAR(8) NOT NULL, 
    [CORREO] NVARCHAR(50) NOT NULL, 
    [FECHA_NACIMIENTO] DATE NOT NULL, 
    [EDAD] INT NOT NULL, 
    [NUMERO_LICENCIA] NVARCHAR(11) NOT NULL, 
    [FECHA_EXPIRACION] DATE NOT NULL, 
    [EMPRESA] INT NOT NULL, 
    [ESTADO] NVARCHAR(10) NOT NULL, 
    CONSTRAINT [FK_TBL_CHOFER_EMPRESA] FOREIGN KEY ([EMPRESA]) REFERENCES [TBL_EMPRESA]([CEDULA_JURIDICA])
)
