CREATE TABLE [dbo].[TBL_ROLE_VISTA]
(
	[ROLE_ID] NVARCHAR(50) NOT NULL, 
    [VISTA_ID] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK_TBL_ROLE_VISTA] PRIMARY KEY ([ROLE_ID], [VISTA_ID]), 
    CONSTRAINT [FK_TBL_ROLE_VISTA_ROLE] FOREIGN KEY (ROLE_ID) REFERENCES [TBL_ROLE](ROLE_ID), 
    CONSTRAINT [FK_TBL_ROLE_VISTA_VISTA] FOREIGN KEY (VISTA_ID) REFERENCES [TBL_VISTA]([VISTA_ID]) )
