CREATE TABLE [dbo].[TBL_LINEA](
	[LINEA_ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_LINEA] [nvarchar](45) NULL DEFAULT (NULL),
	[ESTADO] NVARCHAR(10) NOT NULL,
	[TERMINAL_ID] [int] NOT NULL,
	[ESPACIOS_PARQUEO] INT NOT NULL, 
    [EMPRESA_ID] INT NOT NULL, 
    CONSTRAINT [PK_TBL_LINEA_LINEA_ID] PRIMARY KEY CLUSTERED
	([LINEA_ID] ASC),
	CONSTRAINT [TBL_LINEA$FK_LINEA_TERMINAL] FOREIGN KEY([TERMINAL_ID]) REFERENCES [dbo].[TBL_TERMINAL] ([TERMINAL_ID]), 
    CONSTRAINT [FK_TBL_LINEA_EMPRESA] FOREIGN KEY ([EMPRESA_ID]) REFERENCES [TBL_EMPRESA]([CEDULA_JURIDICA])
) 

