CREATE TABLE [dbo].[TBL_HISTORIAL_PASSWORD]
(
	[PASSWORD_SET] DATETIME NOT NULL , 
    [EMAIL] NVARCHAR(50) NOT NULL, 
    [PASSWORD_HASH] NVARCHAR(24) NOT NULL,
    PRIMARY KEY ([EMAIL], [PASSWORD_SET]), 
    CONSTRAINT [FK_TBL_HISTORIAL_PASSWORD_USUARIO] FOREIGN KEY ([EMAIL]) REFERENCES [TBL_USUARIO]([EMAIL])
)
