CREATE TABLE [dbo].[TBL_SOLICITUDES]
(
	[ID_SOLICITUD] NVARCHAR(50) NOT NULL, 
    [TERMINAL_ID] INT NOT NULL, 
    [CEDULA_JURIDICA] INT NOT NULL, 
    [EMAILS] NVARCHAR(MAX) NOT NULL, 
    [EMAIL_SOLICITANTE] NVARCHAR(50) NOT NULL, 
    [ESTADO] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK_TBL_SOLICITUDES] PRIMARY KEY ([ID_SOLICITUD]), 
    CONSTRAINT [FK_TBL_SOLICITUDES_TERMINAL] FOREIGN KEY (TERMINAL_ID) REFERENCES [TBL_TERMINAL]([TERMINAL_ID]), 
)
