CREATE TABLE [dbo].[TBL_REQUESITO](
	[PERMISOS_ID] [int] IDENTITY(1,1) NOT NULL,
	[PERMISO] [nvarchar](45) NOT NULL,
	[ESTADO] NVARCHAR(50) NOT NULL,
	[PLACA] NVARCHAR(50) NOT NULL,
	CONSTRAINT [PK_TBL_REQUESITO_PERMISOS_ID] PRIMARY KEY CLUSTERED ([PERMISOS_ID] ASC,[PLACA] ASC),
	CONSTRAINT [TBL_REQUESITO$FK_TBL_PERMISOS_TBL_BUS] FOREIGN KEY([PLACA]) REFERENCES [dbo].[TBL_BUS] ([PLACA])
)