CREATE TABLE [dbo].[TBL_RUTA](
	[RUTA_ID] [int] IDENTITY(1,1) NOT NULL,
	[RUTA_DESCRIPCION] [nvarchar](100) NOT NULL,
	[JSON_ROUTE] NVARCHAR(MAX) NOT NULL,
	[LATITUDE_DESTINO] [decimal](20, 17) NOT NULL,
	[LONGITUDE_DESTINO] [decimal](20, 17) NOT NULL,
	[DISTANCIA] DECIMAL(10, 3) NOT NULL,
	[LINEA_ID] INT NOT NULL,
	[TERMINAL_ID] INT NOT NULL,
	[TARIFA_ID] INT NOT NULL, 
    [ESTADO] NVARCHAR(10) NOT NULL, 
    CONSTRAINT [PK_TBL_RUTA] PRIMARY KEY ([RUTA_ID]), 
    CONSTRAINT [FK_TBL_RUTA_LINEA] FOREIGN KEY ([LINEA_ID]) REFERENCES [TBL_LINEA]([LINEA_ID]), 
    CONSTRAINT [FK_TBL_RUTA_TERMINAL] FOREIGN KEY ([TERMINAL_ID]) REFERENCES [TBL_TERMINAL]([TERMINAL_ID]), 
    CONSTRAINT [FK_TBL_RUTA_TARIFA] FOREIGN KEY ([TARIFA_ID]) REFERENCES [TBL_TARIFA]([ROUTE_ID])
)