CREATE TABLE [dbo].[TBL_VISTA](
	[VISTA_ID] NVARCHAR(50)  NOT NULL,
	[VISTA_NOMBRE] NVARCHAR(50)  NOT NULL,
	[DESCRIPCION] [nvarchar](100) NOT NULL,
	[URL] [nvarchar](100) NOT NULL,
	[ICON] NVARCHAR(50) NOT NULL, 
    [APP_CONTROLLER] NVARCHAR(50) NULL, 
    [APP_CONTROLLER_ACTION] NVARCHAR(50) NULL, 
    [SHOW_MENU] BIT NOT NULL DEFAULT 1, 
    CONSTRAINT [PK_TBL_VISTA] PRIMARY KEY ([VISTA_ID]) 
)
