CREATE TABLE [dbo].[TBL_USUARIO](
	[EMAIL] [nvarchar](50) NOT NULL,
    [PASSWORD_SALT] NVARCHAR(24) NOT NULL,
	[PASSWORD_HASH] NVARCHAR(24) NOT NULL, 
	[PASSWORD_LAST_SET] DATeTIME NOT NULL,
	[IDENTIFICACION] NVARCHAR(50) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[APELLIDOS] [nvarchar](50) NOT NULL,
	[FECHA_NACIMIENTO] DATE NOT NULL,
	[ESTADO] NVARCHAR(50) NOT NULL,
	[ROLE_ID] NVARCHAR(50) NOT NULL,
	[NOTIFY_USER_AT] DECIMAL(18, 4) NULL, 
    [PHONE] INT NOT NULL, 
    [TERMINAL_ID] INT NULL DEFAULT 0, 
    [RESET_TOKEN] NVARCHAR(50) NULL DEFAULT null, 
    CONSTRAINT [PK_TBL_USUARIO] PRIMARY KEY ([EMAIL]), 
    CONSTRAINT [FK_TBL_USUARIO_ROLE] FOREIGN KEY (ROLE_ID) REFERENCES [TBL_ROLE]([ROLE_ID]), 
    CONSTRAINT [FK_TBL_USUARIO_TERMINAL] FOREIGN KEY ([TERMINAL_ID]) REFERENCES [TBL_TERMINAL]([TERMINAL_ID])
)