CREATE TABLE [dbo].[TBL_TARJETA](
	[CODIGO_UNICO] NVARCHAR(50) NOT NULL UNIQUE,
	[SALDO_DISPONIBLE] DECIMAL(18, 4) NOT NULL,
	[TERMINAL_ID] [int] NOT NULL,
	[USUARIO] [nvarchar](50) NOT NULL,
	[TIPOTARJETA_ID] [int] NOT NULL,
	[CONVENIO_ID] [int] NULL DEFAULT (NULL),
	[ESTADO_TARJETA_ID] [int] NOT NULL,
	CONSTRAINT [PK_TBL_TARJETA_TARJETA_ID] PRIMARY KEY CLUSTERED ([CODIGO_UNICO] ASC),
	CONSTRAINT [TBL_TARJETA$FK_TARJETA_TERMINAL] FOREIGN KEY([TERMINAL_ID]) REFERENCES [dbo].[TBL_TERMINAL] ([TERMINAL_ID]),
	CONSTRAINT [TBL_TARJETA$FK_TARJETA_TIPOTARJETA] FOREIGN KEY([TIPOTARJETA_ID]) REFERENCES [dbo].[TBL_TIPOTARJETA] ([TIPOTARJETA_ID]),
	CONSTRAINT [TBL_TARJETA$FK_TBL_TARJETA_TBL_CONVENIO] FOREIGN KEY([CONVENIO_ID]) REFERENCES [dbo].[TBL_CONVENIO] ([CEDULA_JURIDICA]),
	CONSTRAINT [TBL_TARJETA$FK_TBL_TARJETA_TBL_ESTADO_TARJETA] FOREIGN KEY([ESTADO_TARJETA_ID]) REFERENCES [dbo].[TBL_ESTADO_TARJETA] ([TBL_ESTADO_TARJETA_ID]), 
    CONSTRAINT [FK_TBL_TARJETA_USUARIO] FOREIGN KEY ([USUARIO]) REFERENCES [TBL_USUARIO]([EMAIL])
)