CREATE TABLE [dbo].[TBL_QUEJAS](
	[QUEJAS_ID] [int] IDENTITY(1,1) NOT NULL,
	[DETALLE_QUEJA] [nvarchar](1000) NOT NULL,
	[RUTA] INT NOT NULL,
	[CHOFER] NVARCHAR(50) NULL,
    [PLACA] NVARCHAR(50) NULL, 
    [HORA] DATETIME NOT NULL, 
    [ESTADO] NVARCHAR(10) NOT NULL, 
    CONSTRAINT [PK_TBL_QUEJAS_QUEJAS_ID] PRIMARY KEY CLUSTERED ([QUEJAS_ID] ASC), 
    CONSTRAINT [FK_TBL_QUEJAS_CHOFER] FOREIGN KEY ([CHOFER]) REFERENCES [TBL_CHOFER]([CEDULA]), 
    CONSTRAINT [FK_TBL_QUEJAS_RUTA] FOREIGN KEY ([RUTA]) REFERENCES [TBL_RUTA]([RUTA_ID])
) 