CREATE TABLE [dbo].[TBL_BUS](
	[PLACA] NVARCHAR(50) NOT NULL,
    [EMPRESA] INT NOT NULL, 
	[CAPACIDAD_SENTADO] [int] NOT NULL,
	[CAPACIDAD_DEPIE] [int] NOT NULL,
	[ASIENTO_DISCAPACITADO] [int] NOT NULL,
	[ESTADO] NVARCHAR(50) NOT NULL,
    CONSTRAINT [PK_TBL_BUS_PLACA] PRIMARY KEY CLUSTERED ([PLACA] ASC), 
    CONSTRAINT [FK_TBL_BUS_EMPRESA] FOREIGN KEY (EMPRESA) REFERENCES [TBL_EMPRESA]([CEDULA_JURIDICA])
)