CREATE TABLE [dbo].[TBL_CONFIGURACION_TERMINAL]
(
    [TERMINAL_ID] INT NOT NULL, 
    [CANTIDAD_QUEJAS_SANCION] INT NOT NULL DEFAULT 5, 
    [COSTO_PARQUEO_HORA] DECIMAL(18, 2) NOT NULL DEFAULT 500, 
    [COSTO_PARQUEO_DIA] DECIMAL(18, 2) NOT NULL DEFAULT 4000, 
    [MONTO_INICIAL_TARJETA] DECIMAL(18, 2) NOT NULL DEFAULT 3000, 
    [COSTO_PARQUEO_BUS_MES] DECIMAL(18, 2) NOT NULL DEFAULT 30000, 
    [CANTIDAD_TARDIAS_SANCION] INT NOT NULL DEFAULT 5, 
    [CANTIDAD_MINUTOS_TARDIA] INT NOT NULL DEFAULT 10, 
    PRIMARY KEY ([TERMINAL_ID]), 
    CONSTRAINT [FK_TBL_CONFIGURACION_TERMINAL] FOREIGN KEY ([TERMINAL_ID]) REFERENCES TBL_TERMINAL([TERMINAL_ID])
)
