CREATE TABLE [dbo].[TBL_ROLE](
	[ROLE_ID] [nvarchar](50) NOT NULL,
	[DESCRIPCION] NVARCHAR(100) NOT NULL, 
	[HOMEPAGE] NVARCHAR(100) NOT NULL,
	[ESTADO] NVARCHAR(10) NOT NULL, 
    CONSTRAINT [PK_TBL_ROLE] PRIMARY KEY ([ROLE_ID]) 
)