CREATE TABLE [dbo].[TBL_ESTADO_TARJETA](
	[TBL_ESTADO_TARJETA_ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ESTADO] [nvarchar](45) NOT NULL,
	CONSTRAINT [PK_TBL_ESTADO_TARJETA_TBL_ESTADO_TARJETA_ID] PRIMARY KEY CLUSTERED ([TBL_ESTADO_TARJETA_ID] ASC)
)