CREATE TABLE [dbo].[TBL_PARQUEO](
	[PARQUEO_ID] [int] IDENTITY(1,1) NOT NULL,
	[ESPACIO_TOTAL] [int] NULL DEFAULT (NULL) ,
	[ESPACIO_DISPONIBLE] [int] NULL DEFAULT (NULL) ,
	[ALQUILER_MENSUAL] [int] NOT NULL,
	[ESTADO] [smallint] NOT NULL,
	[TERMINAL_ID] [int] NOT NULL,
	CONSTRAINT [PK_TBL_PARQUEO_PARQUEO_ID] PRIMARY KEY CLUSTERED ([PARQUEO_ID] ASC),
	CONSTRAINT [TBL_PARQUEO$FK_PARQUEO_TERMINAL] FOREIGN KEY([TERMINAL_ID]) REFERENCES [dbo].[TBL_TERMINAL] ([TERMINAL_ID])
) 