CREATE TABLE [dbo].[TBL_RECORRIDO](
	[RECORRIDO_ID] [int] IDENTITY(1,1) NOT NULL,
	[HORA_SALIDA] DATETIME NULL DEFAULT (NULL),
	[HORA_LLEGADA] DATETIME NULL DEFAULT (NULL),
	[BUS_PLACA] NVARCHAR(50) NOT NULL,
	[CHOFER_CEDULA] NVARCHAR(50) NOT NULL,
	[RUTA_ID] [int] NOT NULL,
	[CANTIDAD_PASAJEROS] INT NOT NULL DEFAULT 0, 
    [HORARIO] TIME(0) NOT NULL, 
    [TARDIA] INT NULL DEFAULT 0, 
    CONSTRAINT [PK_TBL_RECORRIDO_RECORRIDO_ID] PRIMARY KEY CLUSTERED ([RECORRIDO_ID] ASC),
	CONSTRAINT [TBL_RECORRIDO$FK_RECORRIDO_BUS] FOREIGN KEY([BUS_PLACA]) REFERENCES [dbo].[TBL_BUS] ([PLACA]),
	CONSTRAINT [TBL_RECORRIDO$FK_RECORRIDO_RUTA] FOREIGN KEY([RUTA_ID]) REFERENCES [dbo].[TBL_RUTA] ([RUTA_ID]),
	CONSTRAINT [TBL_RECORRIDO$FK_RECORRIDO_CHOFER] FOREIGN KEY([CHOFER_CEDULA]) REFERENCES [dbo].[TBL_CHOFER] ([CEDULA])
)