CREATE TABLE [dbo].[TBL_APP_CLAIM]
(
	[APP_CLAIM_ID] NVARCHAR(50) NOT NULL , 
    [TYPE] NVARCHAR(50) NOT NULL, 
    [API_CONTROLLER] NVARCHAR(50) NULL, 
    [API_CONTROLLER_ACTION] NVARCHAR(50) NULL, 
    CONSTRAINT [PK_TBL_CLAIM] PRIMARY KEY ([APP_CLAIM_ID])
)
