CREATE TABLE [dbo].[TBL_TARIFA]
(
	[ROUTE_ID] INT NOT NULL PRIMARY KEY, 
    [ROUTE_NAME] NVARCHAR(100) NOT NULL, 
    [OPERATOR] NVARCHAR(100) NOT NULL, 
    [REGULAR_FARE] DECIMAL(10, 2) NOT NULL
)
