CREATE TABLE [dbo].[TBL_MULTA]
(
	[MULTA_ID] INT NOT NULL IDENTITY(1,1), 
    [EMPRESA] INT NOT NULL, 
    [MONTO] INT NOT NULL, 
    [FECHA] DATETIME NOT NULL, 
    [DETALLE] NVARCHAR(500) NOT NULL, 
    [ESTADO] NVARCHAR(10) NOT NULL, 
    PRIMARY KEY ([MULTA_ID]), 
    CONSTRAINT [FK_TBL_MULTA_EMPRESA] FOREIGN KEY ([EMPRESA]) REFERENCES [TBL_EMPRESA]([CEDULA_JURIDICA]) 
)
